mod attr_ok;
mod duplicated_axiom;
mod duplicated_impl;
mod duplicated_spec;
mod duplicated_type;
mod invalid_impl_target;
mod invalid_spec_target;
mod name_conflict_on_impl_and_spec;
mod name_conflict_on_type_and_axiom;
