[package]
name = "rusmart-smt-mock"
description = "Mock macros for SMT model derivation testing"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"
edition = "2021"

[lib]
proc-macro = true