[workspace]
members = [
    # ordered and grouped loosely by dependency relation
    "utils",
    "cli",
    "smt/stdlib",
    "smt/remark",
    "smt/derive",
    "smt/testing",
    "lang/rego",
]
resolver = "2"
