[package]
name = "rusmart-cli"
description = "Command line interfnace for the Rusmart project"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive"] }
log = "0.4.22"
tempfile = "3.10.1"
rusmart-utils = { path = "../utils" }