[package]
name = "rusmart-utils"
description = "Utilities shared amonst various crates in Rusmart"
version = "0.1.0"
authors = ["Meng Xu <meng.xu.cs@uwaterloo.ca>"]
license = "GPL-3.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
log = "0.4.22"
num_cpus = "1.16.0"
simplelog = "0.12.2"