[book]
authors = ["Meng Xu"]
language = "en"
multilingual = false
src = "src"
title = "Rusmart Language"

[build]
create-missing = false

[rust]
edition = "2021"

[output.html.playground]
runnable = true